//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouKnowServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YouKnowEntities : DbContext
    {
        public YouKnowEntities()
            : base("name=YouKnowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Attire> Attires { get; set; }
        public virtual DbSet<AttireTag> AttireTags { get; set; }
        public virtual DbSet<Blood> Bloods { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Congestion> Congestions { get; set; }
        public virtual DbSet<CongestionTag> CongestionTags { get; set; }
        public virtual DbSet<CongestionType> CongestionTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Custom> Customs { get; set; }
        public virtual DbSet<CustomTag> CustomTags { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Disaster> Disasters { get; set; }
        public virtual DbSet<DisasterTag> DisasterTags { get; set; }
        public virtual DbSet<DisasterType> DisasterTypes { get; set; }
        public virtual DbSet<Disease> Diseases { get; set; }
        public virtual DbSet<DiseaseTag> DiseaseTags { get; set; }
        public virtual DbSet<Festival> Festivals { get; set; }
        public virtual DbSet<FestivalTag> FestivalTags { get; set; }
        public virtual DbSet<Geo> Geos { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<HospitalTag> HospitalTags { get; set; }
        public virtual DbSet<Missing> Missings { get; set; }
        public virtual DbSet<MissingTag> MissingTags { get; set; }
        public virtual DbSet<MissingType> MissingTypes { get; set; }
        public virtual DbSet<Org> Orgs { get; set; }
        public virtual DbSet<OrgType> OrgTypes { get; set; }
        public virtual DbSet<OrgUser> OrgUsers { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<ReligionTag> ReligionTags { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReportType> ReportTypes { get; set; }
        public virtual DbSet<Sensitivity> Sensitivities { get; set; }
        public virtual DbSet<SensitivityTag> SensitivityTags { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<SurvivalGuide> SurvivalGuides { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TagType> TagTypes { get; set; }
        public virtual DbSet<TreatingHospital> TreatingHospitals { get; set; }
        public virtual DbSet<Wanted> Wanteds { get; set; }
        public virtual DbSet<WantedTag> WantedTags { get; set; }
    }
}
